# Site settings
title: Dingzhong Zhang
email1: dingzhong.zhang@mail.mcgill.ca
email2: dzzhang96@sjtu.edu.cn
description: > # this means to ignore newlines until "baseurl:"
  Actively looking for internship position in related fields. 
  Feel free to contact me <script type="text/javascript" src="//rf.revolvermaps.com/0/0/9.js?i=57pwock4ytn&amp;t=%3A-%29" async="async"></script>
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://dzzhang96.github.io/" # the base hostname & protocol for your site
github_username: dzzhang96
facebook_username: dzzhang96
instagram_username: dzzhang96
linkedin_username: dingzhong-zhang-763604103

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "Graduate Student"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""