# Site settings
title: Dingzhong Zhang
email1: dingzhong.zhang@mail.mcgill.ca
email2: dzzhang96@sjtu.edu.cn
description: > # this means to ignore newlines until "baseurl:"
  If you are interested in my experience, 
  please feel free to contact me. <div id="clustrmaps-container" style="display:none;"><script type="text/javascript" id="clustrmaps" src="//clustrmaps.com/map_v2.js?d=XfiAbOT8Fvf9wKTEvRkXvnM8BfAQV8YHBh-PaHABTo8&cl=ffffff&w=a"></script></div>

baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://dzzhang96.github.io/" # the base hostname & protocol for your site
github_username: dzzhang96
facebook_username: dzzhang96
instagram_username: dzzhang96
linkedin_username: dingzhong-zhang-763604103
googlescholar_username: yZc5uicAAAAJ

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "R&D Engineer"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""